#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: spring_email_send_db

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${YOUR EMAIL}
EMAIL_PASSWORD: ${YOUR APP PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}